export const ADD_FILE = 'ADD_FILE'
export const SET_EDITED_FILE = 'SET_EDITED_FILE'

export const ENABLE_TOOLBAR = 'ENABLE_TOOLBAR'
export const DISABLE_TOOLBAR = 'DISABLE_TOOLBAR'

export const ZOOM_OUT = 'ZOOM_OUT'
export const ZOOM_IN = 'ZOOM_IN'
export const ZOOM_CUSTOM = 'ZOOM_CUSTOM'

export const PAGE_DOWN = 'PAGE_DOWN'
export const PAGE_UP = 'PAGE_UP'
export const PAGE_CUSTOM = 'PAGE_CUSTOM'

export const CREATE_SPLIT_PREVIEW = 'CREATE_SPLIT_PREVIEW'

export const SET_CURRENT_LEFTPANE_VIEW = 'SET_CURRENT_LEFTPANE_VIEW'
