//FILE
export const ADD_FILE = 'ADD_FILE'
export const SET_SPLIT_FILE = 'SET_SPLIT_FILE'
export const SET_EDITED_FILE = 'SET_EDITED_FILE'
export const RESET_AFFECTED_PAGE_NUM = 'RESET_AFFECTED_PAGE_NUM'
//TOOLBAR
export const ENABLE_TOOLBAR = 'ENABLE_TOOLBAR'
export const DISABLE_TOOLBAR = 'DISABLE_TOOLBAR'
//ZOOM
export const ZOOM_OUT = 'ZOOM_OUT'
export const ZOOM_IN = 'ZOOM_IN'
export const ZOOM_CUSTOM = 'ZOOM_CUSTOM'
//PAGE TURN
export const PAGE_DOWN = 'PAGE_DOWN'
export const PAGE_UP = 'PAGE_UP'
export const PAGE_CUSTOM = 'PAGE_CUSTOM'
//SPLITTER
export const CREATE_SPLIT_PREVIEW = 'CREATE_SPLIT_PREVIEW'
//LEFT PANE
export const SET_CURRENT_LEFTPANE_VIEW = 'SET_CURRENT_LEFTPANE_VIEW'
export const OPEN_LEFT_PANE = 'OPEN_LEFT_PANE'
export const CLOSE_LEFT_PANE = 'CLOSE_LEFT_PANE'
